"""Unit Unique together

Revision ID: ec211e685f34
Revises: ef389f9c4716
Create Date: 2022-07-23 10:37:31.945759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec211e685f34'
down_revision = 'ef389f9c4716'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unit_name_key', 'unit', type_='unique')
    op.create_unique_constraint(None, 'unit', ['user_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unit', type_='unique')
    op.create_unique_constraint('unit_name_key', 'unit', ['name'])
    # ### end Alembic commands ###
