"""Add link to user

Revision ID: ef389f9c4716
Revises: 2980a5855f59
Create Date: 2022-07-23 10:18:04.352345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef389f9c4716'
down_revision = '2980a5855f59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deal', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_deal_user_id'), 'deal', ['user_id'], unique=False)
    op.create_foreign_key(None, 'deal', 'user', ['user_id'], ['id'])
    op.add_column('item', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_item_user_id'), 'item', ['user_id'], unique=False)
    op.create_foreign_key(None, 'item', 'user', ['user_id'], ['id'])
    op.add_column('unit', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_unit_user_id'), 'unit', ['user_id'], unique=False)
    op.create_foreign_key(None, 'unit', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unit', type_='foreignkey')
    op.drop_index(op.f('ix_unit_user_id'), table_name='unit')
    op.drop_column('unit', 'user_id')
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_index(op.f('ix_item_user_id'), table_name='item')
    op.drop_column('item', 'user_id')
    op.drop_constraint(None, 'deal', type_='foreignkey')
    op.drop_index(op.f('ix_deal_user_id'), table_name='deal')
    op.drop_column('deal', 'user_id')
    # ### end Alembic commands ###
